os: linux
dist: bionic
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-9
        - python3
        - python3-pip 
install:
  - pip3 install --user jinja2

env:
    - MAKEFLAGS='-j8 --output-sync=target'

scripts:
  - python3 -m unittest src/display.py
  - ./ovo.sh gen

  - export MAKEFLAGS='-j8 --output-sync=target'
  - CXX='g++' CXXFLAGS='-std=c++11 -fopenmp' ./ovo.sh run test_src/cpp/hierarchical_parallelism/
  - ./ovo.sh display
  - CXX='g++' CXXFLAGS='-std=c++17 -fopenmp' ./ovo.sh run test_src/cpp/math_cpp{11,17}
  - ./ovo.sh display

  - FX='gfortran' FFLAGS='-fopenmp' ./ovo.sh run test_src/fortran/hierarchical_parallelism/
  - ./ovo.sh display
