dist: bionic
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - python3
      - python3-pip

scripts:
  - python3 -m unittest src/display.py
  - ./ovo.sh gen

  - export MAKEFLAGS='-j8 --output-sync=target'
  
  - export CXX='g++'
  - CXXFLAGS='-std=c++11' ./ovo.sh run --no_omp_call test_src/cpp/hierarchical_parallelism/ 
  - ./ovo.sh display
  - CXXFLAGS='-std=c++17' ./ovo.sh run test_src/cpp/math_cpp{11,17}
  - ./ovo.sh display

  - FC='gfortran' ./ovo.sh run --no_omp_call test_src/fortran/hierarchical_parallelism/
  - ./ovo.sh display
