dist: bionic
os: linux

git:
    submodules: false

jobs:
  include:
  - name: unittest
    script:
    - python3 -m unittest src/report.py
    - python3 -m doctest  src/gtest.py

  - name: gcc [no omp]
    compiler: gcc
    env: 
      - CXX='g++-9'
      - CXXFLAGS='-std=c++11'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - g++-9 
        - python3
    script:
    - ./ovo.sh run test_src/cpp
    - ./ovo.sh report --failed

  - name: gcc [host omp]
    compiler: gcc
    env: 
      - CXX='g++-9'
      - CXXFLAGS='-fopenmp -std=c++11'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - g++-9 
        - python3
    script:
    - ./ovo.sh run test_src/cpp
    - ./ovo.sh report --failed

  - name: gfortran [no omp]
    compiler: gfortran
    env: 
      - FC='gfortran-9'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - gfortran-9 
        - python3
    script:
    - ./ovo.sh run test_src/fortran
    - ./ovo.sh report --failed

  - name: gfortran [omp host]
    compiler: gfortran
    env: 
      - FC='gfortran-9'
      - FFLAGS='-fopenmp'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - gfortran-9 
        - python3
    script:
    - ./ovo.sh run test_src/fortran
    - ./ovo.sh report --failed
 
