os: linux
dist: bionic
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-9
        - python3
        - python3-pip 
install:
  - pip3 install --user jinja2

scripts:
  - python3 -m unittest src/display.py
  - ./ovo.sh gen

  - CXX="g++" CXXFLAGS="-std=c++11 -fopemmp" MAKEFLAGS='-j8 --output-sync=target' ./ovo.sh run test_src/cpp/hp_*
  - ./ovo.sh display
  - CXX="g++" CXXFLAGS="-std=c++17 -fopemmp" MAKEFLAGS='-j8 --output-sync=target' ./ovo.sh run test_src/cpp/math_cpp{11,17}
  - ./ovo.sh display
 
