dist: bionic
os: linux

git:
    submodules: false


jobs:
  include:
  - name: unittest
    script:
    - python3 -m unittest src/display.py

  - name: cpp hierarchical_parallelism no_omp_call
    addons:
      apt:
       sources:
         - ubuntu-toolchain-r-test
       packages:
        - gcc-9 
        - python3

    script:   
    - CXX='g++' CXXFLAGS='-std=c++11 -Wall -Wno-unknown-pragmas' MAKEFLAGS='-j8 --output-sync=target' ./ovo.sh run test_src/cpp/hierarchical_parallelism/ 
    - ./ovo.sh display

  - name: cpp hierarchical_parallelism no_loop
    addons:
      apt:
       sources:
         - ubuntu-toolchain-r-test
       packages:
        - gcc-9 
        - python3

    script:   
    - CXX='g++' CXXFLAGS='-std=c++11 -fopenmp' MAKEFLAGS='-j8 --output-sync=target' ./ovo.sh run --no_loop test_src/cpp/hierarchical_parallelism/ 
    - ./ovo.sh display

  - name: cpp hierarchical_parallelism host
    addons:
      apt:
       sources:
         - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
       packages:
        - clang-9 
        - python3

    before_install:
    - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

    script:   
    - CXX='clang++' CXXFLAGS='-std=c++11 -fopenmp  -fopenmp-version=50' MAKEFLAGS='-j8 --output-sync=target' ./ovo.sh run --no_loop test_src/cpp/hierarchical_parallelism/ 
    - ./ovo.sh display

  - name: cpp hierarchical_parallelism host (power)
    arch:
    - ppc64le

    install:
    - wget -q https://public.dhe.ibm.com/software/server/POWER/Linux/xl-compiler/eval/ppc64le/ubuntu/public.gpg -O- | sudo apt-key add -
    - echo "deb https://public.dhe.ibm.com/software/server/POWER/Linux/xl-compiler/eval/ppc64le/ubuntu/ ${TRAVIS_DIST} main" >> /etc/apt/sources.list
    - sudo apt-get update
    - export XLC_VERSION="$(apt-cache search '^xlc\.[0-9]+\.[0-9]+\.[0-9]+$' | awk '{ print substr($1, 5) }')"
    - sudo apt-get install "xlc.${XLC_VERSION}" "xlc-license-community.${XLC_VERSION}"
    - sudo /opt/ibm/xlC/${XLC_VERSION}/bin/xlc_configure <<< 1 >/dev/null

    script:   
    - CXX='xlC-r' CXXFLAGS='-std=c++11 -qsmp=omp' FC='xlf90_r'  FFLAGS='-qsmp=omp' ./ovo.sh run --no_loop test_src/cpp/hierarchical_parallelism/ 
    - ./ovo.sh display

  - name: "pgcc"
    env:
    - CXX=pgc++
    install:
    - curl 'https://raw.githubusercontent.com/nemequ/pgi-travis/master/install-pgi.sh' | /bin/sh
    
    script:
    - ./ovo.sh run --no_loop test_src/cpp/hierarchical_parallelism/
    - ./ovo.sh display

  - name: cpp math host
    addons:
      apt:
       sources:
         - ubuntu-toolchain-r-test
       packages:
        - gcc-9 
        - python3

    script:
    - CXX='g++' CXXFLAGS='-std=c++17' MAKEFLAGS='-j8 --output-sync=target' ./ovo.sh run test_src/cpp/math_cpp{11,17}
    - ./ovo.sh display

  - name: fortran hierarchical_parallelism no_omp_call
    addons:
      apt:
       sources:
         - ubuntu-toolchain-r-test
       packages:
        - gfortran-9    
        - python3


    script:
    - FC='gfortran' FCFLAGS='-Wall -Wno-unknown-pragmas' MAKEFLAGS='-j8 --output-sync=target' ./ovo.sh run test_src/fortran/hierarchical_parallelism/
    - ./ovo.sh display


  - name: fortran hierarchical_parallelism no_loop
    addons:
      apt:
       sources:
         - ubuntu-toolchain-r-test
       packages:
        - gfortran-9    
        - python3

    script:
    - FC='gfortran' FCFLAGS='-fopenmp' MAKEFLAGS='-j8 --output-sync=target' ./ovo.sh run --no_loop test_src/fortran/hierarchical_parallelism/
    - ./ovo.sh display
