language: cpp

os: linux

dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - python3.7
    - clang-9

compiler:
  - clang
    
python:
  - 3.7

before_install:
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

install:
  - pip3.7 install --user jinja2

scripts:
  - ./omphval.sh gen
  - CXX="clang++" CXXFLAGS="-std=c++17" MAKEFLAGS='-j64 --output-sync=target' ./omphval.sh run tests/hp_*
  - ./omphval.sh display
  - CXX="clang++" CXXFLAGS="-std=c++17" MAKEFLAGS='-j64 --output-sync=target' ./omphval.sh run tests/math_cpp11 tests/math_cpp17
  - ./omphval.sh display
 
