language: python

compiler:
  - clang
  - gcc

python:
  - 3.8

before_install:
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

install:
  - pip install jinja2

scripts:
  - ./omphval.sh gen
  - CXX="clang++" CXXFLAGS="-std=c++17" ./omphval.sh run tests/hp_*
  - ./omphval.sh display
  - CXX="clang++" CXXFLAGS="-std=c++17" ./omphval.sh run tests/math_cpp11 tests/math_cpp17
  - ./omphval.sh display
 
