dist: bionic
os: linux

git:
    submodules: false

jobs:
  include:
  - name: unittest
    script:
    - python3 -m unittest src/display.py
    - python3 -m doctest -v src/gtest.py

  - name: gcc
    compiler: gcc
    env: 
      - CXX='g++'
      - CXXFLAGS='-std=c++11'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - g++-9 
        - python3
    script:
    - ./ovo.sh run test_src/cpp
    - ./ovo.sh report --failed

  - name: gfortran
    compiler: gfortran
    env: 
      - FC='gfortran'
      - FFLAGS='-Wall -Wno-unknown-pragmas'
    addons:
      apt:
        sources:
         - sourceline: "ppa:ubuntu-toolchain-r/test"
           key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f
        packages:
        - gfortran-9 
        - python3
    script:
    - ./ovo.sh run test_src/fortran
    - ./ovo.sh report
